# Generated by Django 5.2.1 on 2025-06-04 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('inventory', '0002_inventory_ingredient_alter_inventory_product'),
        ('product', '0003_rename_cost_product_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='delivery_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Keltirilgan sana'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Inventar nomi'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Miqdori (gramm)'),
        ),
    ]
