# Generated by Django 5.2.1 on 2025-06-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('inventory', '0003_inventory_note_alter_inventory_delivery_at_and_more'),
        ('product', '0003_rename_cost_product_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
