# Generated by Django 5.2.1 on 2025-06-03 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Kassadagi jami pul')),
                ('total_salary', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Jami oyliklar')),
                ('total_product_price', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Sotib olingan mahsulotlarga ketgan pul')),
                ('total_benefit', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Jami foyda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventories', models.ManyToManyField(related_name='payments_inventory', to='inventory.inventory', verbose_name='Inventarlar')),
                ('users', models.ManyToManyField(related_name='payments_user', to=settings.AUTH_USER_MODEL, verbose_name='Ishchilar')),
            ],
        ),
    ]
