# Generated by Django 5.2.1 on 2025-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('meal', '0002_alter_meal_portion_alter_meal_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='meal',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meal',
            field=models.ManyToManyField(related_name='ingredient_set', to='meal.meal'),
        ),
    ]
