# Generated by Django 5.2.1 on 2025-06-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_month', models.DateField()),
                ('total_expense', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total_benefit_or_damage', models.IntegerField(choices=[(1, 'Benefit'), (2, 'Damage'), (3, 'Did not Change ')], default=3)),
                ('money_left', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total_product', models.BigIntegerField(blank=True, default=0, null=True)),
                ('left_product', models.BigIntegerField(blank=True, default=0, null=True)),
                ('product_went_out', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_benefit', models.BigIntegerField(blank=True, default=0, null=True)),
                ('payment', models.ManyToManyField(related_name='payment', to='payment.payment')),
            ],
        ),
    ]
