# Generated by Django 5.2.1 on 2025-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
        ('product', '0003_rename_cost_product_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='portion',
            field=models.PositiveIntegerField(default=1, verbose_name='Porsiya soni'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(related_name='meals', to='product.product'),
        ),
    ]
