# Generated by Django 5.2.1 on 2025-06-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='meals', to='ingredient.ingredient', verbose_name='Ingredientlar'),
        ),
    ]
