# Generated by Django 5.2.1 on 2025-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_remove_ingredient_meal_ingredient_meal'),
        ('meal', '0002_alter_meal_portion_alter_meal_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='meals', to='ingredient.ingredient'),
        ),
    ]
