# Generated by Django 5.2.1 on 2025-06-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cooking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
