# Generated by Django 5.2.1 on 2025-06-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_meal_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='available_portions',
            field=models.IntegerField(default=0, help_text='Mavjud porsiyalar soni'),
        ),
    ]
