# Generated by Django 5.2.1 on 2025-05-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_min_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_per_unit',
        ),
    ]
