# Generated by Django 5.2.1 on 2025-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_cost_product_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litr'), ('pcs', 'Dona')], default='kg', max_length=10, verbose_name='O‘lchov birligi'),
        ),
    ]
