# Generated by Django 5.2.1 on 2025-06-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('litr', 'Litr'), ('dona', 'Dona')], default='kg', max_length=10, verbose_name='O‘lchov birligi'),
        ),
    ]
